import React, { useEffect, useState, useMemo } from 'react';
import { useLocation, useNavigate } from 'react-router-dom';
import {
  AreaChart, Area, XAxis, YAxis, CartesianGrid, Tooltip as RechartsTooltip, ResponsiveContainer,
  PieChart, Pie, Cell, BarChart, Bar, ComposedChart, Line
} from 'recharts';
import { Activity, Dumbbell, Award, Timer, ChevronLeft, Share2, Sparkles, Flame, TrendingUp, Check } from 'lucide-react';

const COLORS = {
  bench: '#7C3AED',
  dead: '#3B82F6',
  squat: '#34D399',
  ohp: '#F472B6',
  row: '#9CA3AF',
  gradientStart: '#7C3AED',
  gradientEnd: '#A78BFA'
};

const EXERCISE_LABELS = {
  bench: 'Bench Press', dead: 'Deadlift', squat: 'Squat', ohp: 'Overhead Press', row: 'Barbell Row',
};

export default function Analytics() {
  const location = useLocation();
  const navigate = useNavigate();
  const [copied, setCopied] = useState(false);
  const [highlightedRep, setHighlightedRep] = useState(null);
  const chartRef = React.useRef(null);
  const reportRef = React.useRef(null);

  const [sessionData] = useState(() => {
    try {
      const stored = sessionStorage.getItem('lastPrediction');
      return stored ? JSON.parse(stored) : null;
    } catch { return null; }
  });

  const predictionResult = location.state?.result || sessionData?.result;
  
  const exerciseBreakdown = predictionResult?.exercise_breakdown || [];
  const availableExercises = exerciseBreakdown.map(ex => ex.label);
  
  // Check if Targets page pushed an exercise filter via sessionStorage
  const exerciseFilter = sessionStorage.getItem('analyticsExerciseFilter');
  const firstLabel = exerciseFilter && availableExercises.includes(exerciseFilter)
    ? exerciseFilter
    : availableExercises.length > 0 ? availableExercises[0] : 'bench';
  const [activeTab, setActiveTab] = useState(firstLabel);

  // Clear the filter once consumed so it doesn't persist across navigations
  useEffect(() => {
    if (exerciseFilter) sessionStorage.removeItem('analyticsExerciseFilter');
  }, []);
  
  useEffect(() => {
    if (availableExercises.length > 0 && !availableExercises.includes(activeTab)) {
      setActiveTab(availableExercises[0]);
    }
  }, [availableExercises.length, activeTab]);

  const currentExerciseData = exerciseBreakdown.find(ex => ex.label === activeTab) || {};

  const realConfidence = Math.round((predictionResult?.confidence || 0.938) * 100);

  const [activeMetrics, setActiveMetrics] = useState(['Form Score', 'Rhythm']);
  const toggleMetric = (m) => {
    setActiveMetrics(prev => prev.includes(m) ? prev.filter(x => x !== m) : [...prev, m]);
  };

  const shareReport = async () => {
    const lines = [
      `🏋️ EvoFit Session Report`,
      `Exercise: ${EXERCISE_LABELS[activeTab] || activeTab}`,
      `Total Reps: ${totalReps}`,
      `Avg Form Score: ${realConfidence}%`,
      `Overall Consistency: ${overallConsistency}`,
      `Session Duration: ${sessionDuration} (${sessionTimeRange})`,
      `Best Set: ${bestSetSummaryStr}`,
      `Exercises Performed: ${exercisesPerformed}`,
      `---`,
      `Generated by EvoFit Analytics · ${new Date().toLocaleDateString()}`,
    ];
    const text = lines.join('\n');
    try {
      await navigator.clipboard.writeText(text);
      setCopied(true);
      setTimeout(() => setCopied(false), 2500);
    } catch {
      // Fallback for browsers without clipboard API
      const ta = document.createElement('textarea');
      ta.value = text;
      document.body.appendChild(ta);
      ta.select();
      document.execCommand('copy');
      document.body.removeChild(ta);
      setCopied(true);
      setTimeout(() => setCopied(false), 2500);
    }
  };

  const scrollToRep = (repIndex) => {
    setHighlightedRep(repIndex);
    chartRef.current?.scrollIntoView({ behavior: 'smooth', block: 'center' });
    // Clear highlight after 3 seconds
    setTimeout(() => setHighlightedRep(null), 3000);
  };

  const totalReps = (exerciseBreakdown || []).reduce((sum, ex) => sum + (ex?.rep_count || 0), 0) || 0;
  const exercisesPerformed = (availableExercises || []).length || 1;
  const sessionDuration = predictionResult?.duration || 'Unknown';
  const sessionTimeRange = predictionResult?.time_range || 'N/A';
  const overallConsistency = predictionResult?.overall_consistency || '0%';
  
  const bestSetSummaryStr = (predictionResult?.best_set_summary || 'N/A').toString();
  const bestSetParts = bestSetSummaryStr.split(' ');
  const bestSetVal = bestSetParts.length > 1 ? `${bestSetParts[0]} ${bestSetParts[1]}` : 'N/A';
  const bestSetSub = bestSetParts.length > 2 ? bestSetParts.slice(2).join(' ') : 'No data';
  
  const everyRepData = useMemo(() => currentExerciseData.rep_details || [], [currentExerciseData]);
  const rhythmData = useMemo(() => currentExerciseData.rhythm_waveform || [], [currentExerciseData]);
  
  const pieData = (availableExercises || []).map(label => {
    const data = (exerciseBreakdown || []).find(ex => ex?.label === label);
    return { name: EXERCISE_LABELS[label] || label || 'Exercise', value: data?.rep_count || 0, fill: COLORS[label] || COLORS.bench };
  });

  const setBySetData = useMemo(() => {
    const sets = currentExerciseData.set_details || [];
    return sets.map((s) => ({
      name: `Set ${s.set_num}`,
      set_num: s.set_num,
      reps: s.reps,
      confidence: s.confidence,
      rest_before_sec: s.rest_before_sec,
      mean_power: s.mean_power
    }));
  }, [currentExerciseData]);

  const advancedMetrics = useMemo(() => {
    if (!everyRepData || everyRepData.length === 0) return { wobble: 0, con: 0, ecc: 0, ratio: '1.0' };
    let sumW = 0, sumC = 0, sumE = 0;
    everyRepData.forEach(r => {
      sumW += (r.wobble || 0);
      sumC += (r.concentric_sec || 0);
      sumE += (r.eccentric_sec || 0);
    });
    const len = everyRepData.length;
    const avgC = (sumC/len).toFixed(1);
    const avgE = (sumE/len).toFixed(1);
    return {
      wobble: (sumW/len).toFixed(2),
      con: avgC,
      ecc: avgE,
      ratio: avgE > 0 ? (avgC / avgE).toFixed(1) : '1.0'
    };
  }, [everyRepData]);

  const pbBins = useMemo(() => {
    let exc = 0, good = 0, focus = 0;
    const probs = [];
    everyRepData.forEach(r => {
      if (r.score >= 85) exc++;
      else if (r.score >= 70) good++;
      else {
        focus++;
        probs.push(r);
      }
    });
    const t = everyRepData.length || 1;
    return {
      bars: [
        { label: 'Excellent Form', val: `${Math.round((exc/t)*100)}%`, count: exc, color: '#34D399' },
        { label: 'Good Form', val: `${Math.round((good/t)*100)}%`, count: good, color: '#FCD34D' },
        { label: 'Needs Focus', val: `${Math.round((focus/t)*100)}%`, count: focus, color: '#F87171' }
      ],
      problems: probs.slice(0, 3)
    };
  }, [everyRepData]);

  // True average form score derived from per-rep scores (NOT model confidence)
  const avgFormScore = useMemo(() => {
    if (!everyRepData || everyRepData.length === 0) return realConfidence;
    const sum = everyRepData.reduce((acc, r) => acc + (r.score || 0), 0);
    return Math.round(sum / everyRepData.length);
  }, [everyRepData, realConfidence]);

  // Tier label consistent with pbBins thresholds
  const avgFormTier = avgFormScore >= 85 ? 'Excellent' : avgFormScore >= 70 ? 'Good Form' : 'Needs Improvement';

  if (!predictionResult) {
    return (
      <div className="flex-1 flex items-center justify-center p-6 bg-evofit-bg-primary min-h-full">
        <div className="text-center p-12 glass-card max-w-md w-full">
          <div className="w-16 h-16 rounded-full bg-evofit-purple-main/10 flex items-center justify-center mx-auto mb-6">
             <Dumbbell className="text-evofit-purple-main" size={32} />
          </div>
          <h3 className="text-xl font-bold text-evofit-text-primary mb-2">No Session Data</h3>
          <p className="text-evofit-text-secondary mb-8">Upload a session file to view AI performance analytics.</p>
          <button className="premium-gradient text-evofit-text-primary px-6 py-2.5 rounded-xl font-bold hover:-translate-y-0.5 transition-all shadow-lg" onClick={() => navigate('/upload')}>
            Go to Upload
          </button>
        </div>
      </div>
    );
  }

  return (
    <div ref={reportRef} className="flex-1 p-8 md:p-10 overflow-y-auto relative z-10 bg-evofit-bg-primary font-inter animate-page-enter">
      
      {/* ── RETURN BUTTON + SHARE ─────────────────────────────────────────── */}
      <div className="mb-4 flex items-center justify-between">
        <button onClick={() => navigate('/upload')} className="bg-transparent border-none text-evofit-text-secondary flex items-center gap-1.5 text-[13px] cursor-pointer p-0 hover:text-evofit-text-primary transition-colors font-semibold">
          <ChevronLeft size={16} /> Return to Upload & Predict
        </button>
        {predictionResult && (
          <button
            onClick={shareReport}
            className={`flex items-center gap-2 px-4 py-2 rounded-xl border text-[13px] font-bold transition-all duration-200 cursor-pointer
              ${copied
                ? 'bg-green-500/10 border-green-500/40 text-green-400'
                : 'bg-evofit-bg-secondary border-evofit-border text-evofit-text-secondary hover:border-evofit-purple-main/40 hover:text-evofit-purple-light hover:bg-evofit-purple-main/5'
              }`}
          >
            {copied ? <><Check size={14} /> Copied!</> : <><Share2 size={14} /> Share Report</>}
          </button>
        )}
      </div>

      {/* ── TABS ───────────────────────────────────────────────────────── */}
      <div className="flex border-b border-evofit-border mb-6">
        {availableExercises.map(tab => {
          const isActive = activeTab === tab;
          return (
            <div 
              key={tab}
              onClick={() => setActiveTab(tab)}
              className={`px-6 py-3 cursor-pointer transition-all duration-200 border-b-[3px] font-semibold text-sm
                ${isActive ? 'text-evofit-purple-light border-evofit-purple-main' : 'text-evofit-text-secondary border-transparent hover:text-evofit-text-primary'}`}
            >
              {EXERCISE_LABELS[tab] || tab}
            </div>
          );
        })}
      </div>

      <div className="animate-page-enter delay-200">
        
        {/* ── KEY METRICS ROW ───────────────────────────────────────────── */}
        <div className="grid grid-cols-2 lg:grid-cols-3 xl:grid-cols-6 gap-4 mb-6">
          {[
            { label: 'Total Reps Context', val: totalReps, sub: 'Entire Session', icon: <Dumbbell size={18} className="text-evofit-purple-light" /> },
            { label: 'Exercises Performed', val: exercisesPerformed, sub: 'Auto-detected', icon: null },
            { label: 'Average Form Score', val: `${avgFormScore}%`, sub: avgFormTier, icon: <Award size={18} className={avgFormScore >= 85 ? 'text-green-400' : avgFormScore >= 70 ? 'text-yellow-400' : 'text-red-400'} /> },
            { label: 'Overall Consistency', val: overallConsistency, sub: 'Calculated Rhythm', icon: <Activity size={18} className="text-blue-400" /> },
            { label: 'Session Duration', val: sessionDuration, sub: sessionTimeRange, icon: <Timer size={18} className="text-pink-400" /> },
            { label: 'Best Set', val: bestSetVal, sub: bestSetSub, icon: <Sparkles size={18} className="text-amber-400" /> }
          ].map((m, i) => (
            <div key={i} className="glass-card p-5 flex flex-col gap-2 shadow-premium-card hover:translate-y-[-2px] transition-transform">
              <div className="flex justify-between items-start">
                <p className="text-[13px] text-evofit-text-secondary m-0 font-medium">{m.label}</p>
                {m.icon && m.icon}
              </div>
              <div>
                <p className="text-[28px] font-extrabold m-0 text-evofit-text-primary leading-tight">{m.val}</p>
                <p className="text-[12px] text-evofit-text-muted m-0 mt-0.5">{m.sub}</p>
              </div>
            </div>
          ))}
        </div>

        {/* ── MAIN CHARTS ROW ────────────────────────────────────────────── */}
        <div className="grid grid-cols-1 lg:grid-cols-[2fr_1fr] gap-5 mb-5">
          
          {/* Every Rep Breakdown */}
          <div ref={chartRef} className="glass-card p-6 shadow-premium-card">
            <div className="flex justify-between mb-5 items-center">
              <div>
                <h3 className="text-base font-bold m-0 text-evofit-text-primary">Every Rep Breakdown</h3>
                <p className="text-[13px] text-evofit-text-muted m-0">Interactive performance tracking</p>
              </div>
              <div className="flex gap-2">
                {['Form Score', 'Rhythm'].map((t) => {
                  const isActive = activeMetrics.includes(t);
                  return (
                    <span key={t} onClick={() => toggleMetric(t)} 
                      className={`text-[12px] px-2.5 py-1 rounded-full cursor-pointer transition-all border
                        ${isActive ? 'bg-evofit-purple-main/20 text-evofit-purple-light border-evofit-purple-main/40 shadow-[0_0_10px_rgba(124,58,237,0.2)]' : 'bg-transparent text-evofit-text-secondary border-evofit-border hover:border-evofit-border-hover'}`}>
                      {t}
                    </span>
                  );
                })}
              </div>
            </div>
            <div className="h-[240px] w-full mt-2">
              <ResponsiveContainer width="100%" height="100%">
                <ComposedChart data={everyRepData} margin={{ top: 10, right: 0, left: -20, bottom: 0 }}>
                  <defs>
                    <linearGradient id="colorScore" x1="0" y1="0" x2="0" y2="1">
                      <stop offset="5%" stopColor="#7C3AED" stopOpacity={0.4}/>
                      <stop offset="95%" stopColor="#7C3AED" stopOpacity={0}/>
                    </linearGradient>
                  </defs>
                  <CartesianGrid strokeDasharray="3 3" vertical={false} stroke="var(--border)" opacity={0.1} />
                  <XAxis dataKey="rep" stroke="var(--text-muted)" fontSize={12} tickLine={false} axisLine={false} />
                  <YAxis stroke="var(--text-muted)" fontSize={12} tickLine={false} axisLine={false} domain={[0, 100]} />
                  <RechartsTooltip 
                    contentStyle={{ borderRadius: '12px', background: 'var(--bg-card)', border: '1px solid var(--border)', fontSize: '12px', boxShadow: 'var(--card-shadow)', color: 'var(--text-primary)' }}
                    itemStyle={{ color: 'var(--purple-main)', fontWeight: 'bold' }}
                  />
                  {activeMetrics.includes('Form Score') && (
                    <Area type="monotone" dataKey="score" stroke="#A78BFA" strokeWidth={3} fillOpacity={1} fill="url(#colorScore)" 
                      activeDot={{ r: 6, fill: 'var(--purple-main)', stroke: 'var(--bg-card)', strokeWidth: 2 }}
                      dot={(props) => {
                        const { cx, cy, payload } = props;
                        if (highlightedRep === null || payload.rep !== highlightedRep) return null;
                        return <circle key={`dot-${payload.rep}`} cx={cx} cy={cy} r={9} fill="#F472B6" stroke="white" strokeWidth={2} className="animate-pulse" />;
                      }}
                    />
                  )}
                  {activeMetrics.includes('Rhythm') && (
                    <Line type="monotone" dataKey="rhythm" stroke="#3B82F6" strokeWidth={2} dot={false} strokeDasharray="5 5" />
                  )}
                </ComposedChart>
              </ResponsiveContainer>
            </div>
          </div>
  
          {/* All Exercises Distribution */}
          <div className="glass-card p-6 shadow-premium-card">
            <h3 className="text-base font-bold m-0 text-evofit-text-primary">All Exercises - Rep Distribution</h3>
            <p className="text-[13px] text-evofit-text-muted m-0 mb-4">Volume breakdown</p>
            <div className="flex items-center h-[200px]">
              <div className="w-1/2 h-full">
                <ResponsiveContainer width="100%" height="100%">
                  <PieChart>
                    <Pie data={pieData} innerRadius={50} outerRadius={80} paddingAngle={4} dataKey="value" stroke="none">
                      {pieData.map((entry, index) => <Cell key={`cell-${index}`} fill={entry.fill} />)}
                    </Pie>
                    <RechartsTooltip 
                      contentStyle={{ borderRadius: '8px', background: 'var(--bg-card)', border: '1px solid var(--border)', fontSize: '12px', boxShadow: 'var(--card-shadow)', color: 'var(--text-primary)' }} 
                    />
                  </PieChart>
                </ResponsiveContainer>
              </div>
              <div className="w-1/2 flex flex-col gap-2.5">
                {pieData.map(d => (
                  <div key={d.name} className="flex items-center gap-2 text-[13px] text-evofit-text-secondary">
                    <div className="w-2.5 h-2.5 rounded-full" style={{ background: d.fill }}></div>
                    <span className="flex-1 truncate">{d.name}</span>
                    <span className="font-bold text-evofit-text-primary">{d.value}</span>
                  </div>
                ))}
              </div>
            </div>
          </div>
        </div>

        {/* ── DEEP ANALYSIS ROW ───────────────────────────────────────────── */}
        <h3 className="text-lg font-extrabold mb-4 mt-3 text-evofit-text-primary">Deep Analysis</h3>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-5 mb-10">
          
          {/* Form Quality */}
          <div className="glass-card p-6 shadow-premium-card">
            <h4 className="text-[15px] font-bold m-0 mb-4 text-evofit-text-primary">Form Quality Breakdown</h4>
            <div className="flex items-end gap-3 mb-6">
              <span className={`text-[42px] font-extrabold leading-none tracking-tighter ${
                avgFormScore >= 85 ? 'text-[#34D399]' : avgFormScore >= 70 ? 'text-[#FCD34D]' : 'text-[#F87171]'
              }`}>{avgFormScore}%</span>
              <div className="flex flex-col mb-1.5 gap-0.5">
                <span className="text-[12px] text-evofit-text-muted font-bold uppercase tracking-wider">Avg. Score</span>
                <span className={`text-[11px] font-extrabold uppercase tracking-wider ${
                  avgFormScore >= 85 ? 'text-[#34D399]' : avgFormScore >= 70 ? 'text-[#FCD34D]' : 'text-[#F87171]'
                }`}>{avgFormTier}</span>
              </div>
            </div>
            
            <div className="flex flex-col gap-3.5 mb-6">
              {pbBins.bars.map(f => (
                <div key={f.label}>
                  <div className="flex justify-between text-[12px] mb-1.5 font-medium">
                    <span className="text-evofit-text-secondary">{f.label}: <strong className="text-evofit-text-primary ml-1">{f.val}</strong></span>
                    <span className="text-evofit-text-muted">{f.count}/{everyRepData.length}</span>
                  </div>
                  <div className="h-1.5 bg-evofit-bg-secondary rounded-full overflow-hidden">
                    <div className="h-full rounded-full transition-all duration-1000 ease-out" style={{ width: f.val, background: f.color }}></div>
                  </div>
                </div>
              ))}
            </div>
            
            {pbBins.problems.length > 0 && (
              <div className="border-t border-evofit-border pt-4">
                 <h5 className="text-[13px] text-evofit-text-primary font-bold m-0 mb-2.5">Problem Reps Identified</h5>
                 {pbBins.problems.map((pr, idx) => (
                   <div key={idx} className="grid grid-cols-[1fr_2fr_1fr] text-[12px] text-evofit-text-muted gap-2 mb-1.5 font-medium items-center">
                     <span>Rep {pr.rep}</span>
                     <span className="text-amber-400">Form Score: {pr.score}</span>
                     <span
                       onClick={() => scrollToRep(pr.rep)}
                       className="text-evofit-purple-light text-right cursor-pointer hover:underline hover:text-evofit-purple-main transition-colors"
                     >
                       ↑ View
                     </span>
                   </div>
                 ))}
              </div>
            )}
          </div>

          {/* Rep Rhythm */}
          <div className="glass-card p-6 shadow-premium-card">
            <div className="flex justify-between items-center mb-1">
               <h4 className="text-[15px] font-bold m-0 text-evofit-text-primary">Rep Rhythm & Consistency</h4>
               <span className="text-[12px] font-extrabold text-[#34D399] bg-[#34D399]/10 px-2 py-0.5 rounded-lg border border-[#34D399]/15">Consistency: {overallConsistency}</span>
            </div>
            <p className="text-[12px] text-evofit-text-muted m-0 mb-5">{overallConsistency === '0%' ? 'No rhythm data recorded' : 'Tracked via peak-to-peak duration variance'}</p>
            
            <div className="h-[160px] w-full mt-2 mb-4">
              <ResponsiveContainer width="100%" height="100%">
                <ComposedChart data={rhythmData}>
                   <defs>
                    <linearGradient id="colorWave" x1="0" y1="0" x2="0" y2="1">
                      <stop offset="5%" stopColor="#3B82F6" stopOpacity={0.8}/>
                      <stop offset="95%" stopColor="#3B82F6" stopOpacity={0}/>
                    </linearGradient>
                  </defs>
                  <RechartsTooltip contentStyle={{display: 'none'}} />
                  <Area type="monotone" dataKey="actual" fill="url(#colorWave)" stroke="#22D3EE" strokeWidth={2} />
                  <Line type="monotone" dataKey="ideal" stroke="#F472B6" strokeWidth={2} strokeDasharray="3 3" dot={false} />
                </ComposedChart>
              </ResponsiveContainer>
            </div>
            <div className="flex gap-4 text-[12px] text-evofit-text-secondary justify-center font-bold">
               <span className="flex items-center gap-1.5"><div className="w-2.5 h-0.5 bg-[#F472B6]"/> Ideal benchmark</span>
               <span className="flex items-center gap-1.5"><div className="w-2.5 h-0.5 bg-[#22D3EE]"/> Session profile</span>
            </div>
          </div>

          {/* Advanced Physics: Wobble & TUT */}
          <div className="flex flex-col gap-5">
            
            {/* Wobble / Stability Card */}
            <div className="glass-card p-6 flex flex-1 items-center shadow-premium-card">
              <div className="flex-1">
                 <h4 className="text-[15px] font-bold m-0 mb-1 text-evofit-text-primary">Form Stability (Gyro)</h4>
                 <p className="text-[12px] text-evofit-text-muted m-0 mb-4">Barbell rotational wobble</p>
                 <div className="flex items-end gap-2">
                   <span className="text-[32px] font-extrabold text-evofit-purple-light leading-none tracking-tight">{advancedMetrics.wobble}</span>
                   <span className="text-[12px] text-evofit-text-secondary mb-1 font-bold">var/s</span>
                 </div>
              </div>
              <div className={`w-20 h-20 rounded-full border-4 flex items-center justify-center text-[12px] text-evofit-text-primary font-extrabold shadow-lg
                  ${advancedMetrics.wobble > 2.0 ? 'border-red-500 shadow-red-500/10' : 'border-green-500 shadow-green-500/10'}`}>
                 {advancedMetrics.wobble > 2.0 ? 'Unstable' : 'Tight'}
              </div>
            </div>

            {/* Time Under Tension Card */}
            <div className="glass-card p-6 flex-1 shadow-premium-card">
              <h4 className="text-[15px] font-bold m-0 mb-1 text-evofit-text-primary">Time Under Tension</h4>
              <p className="text-[12px] text-evofit-text-muted m-0 mb-4">Concentric vs Eccentric phases</p>
              
              <div className="flex justify-between text-[13px] mb-2 font-bold uppercase tracking-wide">
                 <span className="text-amber-500">Up: {advancedMetrics.con}s</span>
                 <span className="text-blue-400">Down: {advancedMetrics.ecc}s</span>
              </div>
              <div className="flex h-2 bg-evofit-bg-secondary rounded-full overflow-hidden">
                 <div className="bg-amber-400 h-full" style={{ width: `${(parseFloat(advancedMetrics.con) / (parseFloat(advancedMetrics.con) + parseFloat(advancedMetrics.ecc) || 1)) * 100}%` }}></div>
                 <div className="bg-blue-400 h-full" style={{ width: `${(parseFloat(advancedMetrics.ecc) / (parseFloat(advancedMetrics.con) + parseFloat(advancedMetrics.ecc) || 1)) * 100}%` }}></div>
              </div>
              <div className="text-center mt-3 text-[12px] text-evofit-text-secondary font-bold uppercase tracking-widest">
                 Tempo Ratio <strong className="text-evofit-text-primary ml-1">{advancedMetrics.ratio} : 1</strong>
              </div>
            </div>
            
          </div>

          {/* Set-by-Set Performance */}
          <div className="glass-card p-6 flex flex-col shadow-premium-card">
            <div className="flex justify-between items-center mb-4">
               <h4 className="text-[15px] font-bold m-0 text-evofit-text-primary">Endurance & Recovery</h4>
               <span className="text-[11px] text-evofit-text-muted font-bold uppercase tracking-wider">Power Fatigue Map</span>
            </div>
            <div className="flex gap-3 h-40 items-flex-end justify-between flex-1 pb-6 pt-4 px-2">
               {setBySetData.map((set, i) => {
                 const maxHeight = Math.max(...setBySetData.map(s => s.reps)) || 15;
                 const hPct = `${(set.reps/maxHeight)*100}%`;
                 return (
                   <React.Fragment key={set.name}>
                     {i > 0 && (
                       <div className="self-center z-10 -mx-2 bg-evofit-bg-secondary border border-evofit-border px-1.5 py-0.5 rounded text-[9px] text-evofit-text-muted font-bold">
                         {set.rest_before_sec}s
                       </div>
                     )}
                     <div className="flex flex-col items-center gap-2 flex-1 relative h-full justify-end">
                       <div className="absolute -top-6 text-[10px] text-amber-500 whitespace-nowrap flex flex-col items-center font-bold">
                          <span>{set.mean_power}G</span>
                       </div>
                       <span className="text-[14px] font-extrabold text-evofit-text-primary">{set.reps}</span>
                       <div 
                        className={`w-full max-w-[30px] rounded-t-lg transition-all duration-1000 ease-out
                          ${i===0 ? 'bg-gradient-to-t from-evofit-bg-secondary to-evofit-purple-main' : 'bg-gradient-to-t from-evofit-bg-secondary to-blue-500'}`}
                        style={{ height: hPct }}
                       ></div>
                       <span className="text-[11px] text-evofit-text-muted font-bold uppercase">S{set.set_num}</span>
                     </div>
                   </React.Fragment>
                 );
               })}
            </div>
            
            <div className="mt-4 bg-evofit-bg-secondary p-4 rounded-xl border border-evofit-border shadow-inner">
              <h5 className="text-[13px] font-extrabold m-0 mb-1.5 text-evofit-text-primary flex items-center gap-1.5">
                <Sparkles size={14} className="text-amber-400" /> Key Observation
              </h5>
              <p className="text-[12px] text-evofit-text-secondary leading-relaxed font-medium">
                Your strongest recorded performance interval was {bestSetSummaryStr} based on combined volume density.
              </p>
            </div>
          </div>

        </div>
      </div>
    </div>
  );
}
